/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Invoice {
  'status' : InvoiceStatus,
  'balanceAmount' : bigint,
  'retailerCode' : string,
  'retailerName' : string,
  'salesmanName' : string,
  'invoiceDate' : string,
  'invoiceNumber' : string,
}
export type InvoiceStatus = { 'paid' : null } |
  { 'unpaid' : null } |
  { 'excess' : null } |
  { 'partiallyPaid' : null };
export interface PaymentEntry {
  'id' : bigint,
  'chequeDate' : [] | [Time],
  'chequeNumber' : [] | [string],
  'retailerCode' : string,
  'bankTransferDate' : [] | [Time],
  'invoiceNumber' : string,
  'createdTimestamp' : Time,
  'paymentMode' : PaymentMode,
  'paymentType' : PaymentType,
  'chequeBankName' : [] | [string],
  'paymentAmount' : bigint,
  'enteredBy' : Principal,
  'transactionId' : [] | [string],
}
export type PaymentMode = { 'cash' : null } |
  { 'bankTransfer' : null } |
  { 'cheque' : null };
export type PaymentType = { 'excessPayment' : null } |
  { 'invoicePayment' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPayment' : ActorMethod<
    [
      string,
      string,
      bigint,
      PaymentType,
      PaymentMode,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [Time],
      [] | [Time],
    ],
    string
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAllData' : ActorMethod<[], undefined>,
  'editPayment' : ActorMethod<
    [
      bigint,
      bigint,
      PaymentType,
      PaymentMode,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [Time],
      [] | [Time],
    ],
    undefined
  >,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAllPayments' : ActorMethod<[], Array<PaymentEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInvoice' : ActorMethod<[string], [] | [Invoice]>,
  'getPaymentHistory' : ActorMethod<[string], Array<PaymentEntry>>,
  'getReportsData' : ActorMethod<
    [
      [] | [Time],
      [] | [Time],
      [] | [string],
      [] | [PaymentType],
      [] | [PaymentMode],
    ],
    {
      'payments' : Array<PaymentEntry>,
      'totalCollected' : bigint,
      'totalExcess' : bigint,
      'pendingBalance' : bigint,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'uploadInvoices' : ActorMethod<[Array<Invoice>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];