/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PaymentType = IDL.Variant({
  'excessPayment' : IDL.Null,
  'invoicePayment' : IDL.Null,
});
export const PaymentMode = IDL.Variant({
  'cash' : IDL.Null,
  'bankTransfer' : IDL.Null,
  'cheque' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const InvoiceStatus = IDL.Variant({
  'paid' : IDL.Null,
  'unpaid' : IDL.Null,
  'excess' : IDL.Null,
  'partiallyPaid' : IDL.Null,
});
export const Invoice = IDL.Record({
  'status' : InvoiceStatus,
  'balanceAmount' : IDL.Nat,
  'retailerCode' : IDL.Text,
  'retailerName' : IDL.Text,
  'salesmanName' : IDL.Text,
  'invoiceDate' : IDL.Text,
  'invoiceNumber' : IDL.Text,
});
export const Time = IDL.Int;
export const PaymentEntry = IDL.Record({
  'id' : IDL.Nat,
  'retailerCode' : IDL.Text,
  'invoiceNumber' : IDL.Text,
  'createdTimestamp' : Time,
  'paymentMode' : PaymentMode,
  'paymentType' : PaymentType,
  'paymentAmount' : IDL.Nat,
  'enteredBy' : IDL.Principal,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPayment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, PaymentType, PaymentMode],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAllData' : IDL.Func([], [], []),
  'editPayment' : IDL.Func(
      [IDL.Nat, IDL.Nat, PaymentType, PaymentMode],
      [],
      [],
    ),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInvoice' : IDL.Func([IDL.Text], [IDL.Opt(Invoice)], ['query']),
  'getPaymentHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PaymentEntry)],
      ['query'],
    ),
  'getReportsData' : IDL.Func(
      [
        IDL.Opt(Time),
        IDL.Opt(Time),
        IDL.Opt(IDL.Text),
        IDL.Opt(PaymentType),
        IDL.Opt(PaymentMode),
      ],
      [
        IDL.Record({
          'payments' : IDL.Vec(PaymentEntry),
          'totalCollected' : IDL.Nat,
          'totalExcess' : IDL.Nat,
          'pendingBalance' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'uploadInvoices' : IDL.Func([IDL.Vec(Invoice)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PaymentType = IDL.Variant({
    'excessPayment' : IDL.Null,
    'invoicePayment' : IDL.Null,
  });
  const PaymentMode = IDL.Variant({
    'cash' : IDL.Null,
    'bankTransfer' : IDL.Null,
    'cheque' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const InvoiceStatus = IDL.Variant({
    'paid' : IDL.Null,
    'unpaid' : IDL.Null,
    'excess' : IDL.Null,
    'partiallyPaid' : IDL.Null,
  });
  const Invoice = IDL.Record({
    'status' : InvoiceStatus,
    'balanceAmount' : IDL.Nat,
    'retailerCode' : IDL.Text,
    'retailerName' : IDL.Text,
    'salesmanName' : IDL.Text,
    'invoiceDate' : IDL.Text,
    'invoiceNumber' : IDL.Text,
  });
  const Time = IDL.Int;
  const PaymentEntry = IDL.Record({
    'id' : IDL.Nat,
    'retailerCode' : IDL.Text,
    'invoiceNumber' : IDL.Text,
    'createdTimestamp' : Time,
    'paymentMode' : PaymentMode,
    'paymentType' : PaymentType,
    'paymentAmount' : IDL.Nat,
    'enteredBy' : IDL.Principal,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPayment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, PaymentType, PaymentMode],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAllData' : IDL.Func([], [], []),
    'editPayment' : IDL.Func(
        [IDL.Nat, IDL.Nat, PaymentType, PaymentMode],
        [],
        [],
      ),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInvoice' : IDL.Func([IDL.Text], [IDL.Opt(Invoice)], ['query']),
    'getPaymentHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PaymentEntry)],
        ['query'],
      ),
    'getReportsData' : IDL.Func(
        [
          IDL.Opt(Time),
          IDL.Opt(Time),
          IDL.Opt(IDL.Text),
          IDL.Opt(PaymentType),
          IDL.Opt(PaymentMode),
        ],
        [
          IDL.Record({
            'payments' : IDL.Vec(PaymentEntry),
            'totalCollected' : IDL.Nat,
            'totalExcess' : IDL.Nat,
            'pendingBalance' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'uploadInvoices' : IDL.Func([IDL.Vec(Invoice)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };